### ISSUE TITLE
remove unnecessary dependencies

### ISSUE THREAD

**Issue by SilenZcience** [shawwn/supports-color-python#4]
Would you be open to drop the `dict = "^2020.12.3"` dependency?

Python has a perfectly fine native implementation of dictionaries. i feel like a small script like [supports-color-python](https://github.com/shawwn/supports-color-python) should not have unnecessarily many dependecies.

Feel free to dismiss this issue if you do not agree.
i would be happy to send a PR :)

**Comment by shawwn** [comment]
Yes, good idea! Thank you. I’d happily merge the PR.

**Comment by SilenZcience** [comment]
i just noticed that by using the native dictionary the usage of [supports-color-python](https://github.com/shawwn/supports-color-python) would change from
```
if supportsColor.stdout:
    print('Terminal stdout supports color')
```
to
```
if supportsColor['stdout']:
    print('Terminal stdout supports color')
```

Am i right to assume that this is not acceptable?

I still think we can drop the dependency and have the same behaviour by using a minimalistic(removing a lot of redundant interface functionality) class like
```
class edict(dict):
    def __getattr__(self, k):
        return self.get(k)
```
which would keep the consistency to the previous usage.

**Comment by shawwn** [comment]
Ah, yes, I forgot about that. Correct, the idea was that the Python code
should look visually similar to the NodeJS library’s code.

Sure, you can refactor it if you want. It’s always nice to drop an external
dependency that might change. But personally I don’t mind either way.

**Comment by SilenZcience** [comment]
is there a problem with the PR?

**Comment by featherbutt** [comment]
This issue is incredibly timely: dict just broke, because it depends on another package by the same author, values, which was removed by PyPi last week.

values according to Wayback Machine: https://web.archive.org/web/20231130082737/https://pypi.org/project/values/
values as of August 16th: https://pypi.org/project/values/

**Comment by shawwn** [comment]
Thank you @SilenZcience and @featherbutt. Sorry for the delay, I've been busy with a new job.

I appreciate the hard work, and for saving the project from dependency problems. It's a nice reminder to keep dependencies to a minimum when it's easy to.
